apiVersion: apps/v1
kind: Deployment
metadata:
    name: forum
spec:
    replicas: 3
    selector:
        matchLabels:
            app: forum
    template:
        metadata:
            labels:
                app: forum
        spec:
            containers:
                - name: forum
                  image: forum
                  ports:
                      - containerPort: 8080
